version: '3.8'
services:
  app:
    build: .
    depends_on:
      - mongo
    volumes:
      - .:/server
      - /server/node_modules
    ports:
      - '3000:3000'
    env_file:
      - .env
    command: ['nodemon', '--exec', 'ts-node', 'src/server.ts']
    environment:
      NODE_ENV: development
  mongo:
    image: mongo
    ports:
      - '27017:27017'
